lvgl:
  anim_time: 0ms
  theme:
    button:
      bg_opa: TRANSP
      border_width: 0
      radius: 0
      text_color: 0x000000
      text_font: ${page_font}
      focused:
        bg_color: 0x000000
        bg_opa: COVER
        text_color: 0xFFFFFF
        border_color: 0x000000
    label:
      text_color: 0x000000
      bg_opa: TRANSP
    spinbox:
      bg_color: 0xFFFFFF
      bg_opa: COVER
      border_width: 2
      border_color: 0x000000
      radius: 0
      text_color: 0x000000
      text_font: ${page_font}
      focused:
        border_color: 0x000000
        border_width: 2
        radius: 0
      selected:
        bg_color: 0x000000
        bg_opa: COVER
        text_color: 0xFFFFFF
